# Generated by Django 3.2.7 on 2021-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('identificador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('unidades', models.PositiveIntegerField()),
                ('precio_sin_impuestos', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.TimeField(auto_now_add=True)),
                ('precio_sin_impuestos', models.PositiveIntegerField(blank=True, null=True)),
                ('porcentaje_impuesto', models.PositiveIntegerField()),
                ('precio_total', models.PositiveIntegerField(blank=True, null=True)),
                ('moneda', models.CharField(max_length=50)),
                ('articulos', models.ManyToManyField(to='pedidos.Articulo')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
